version: '3.8'  
services:
  postgres:
    image: postgres:15-alpine
    restart: "unless-stopped"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - "postgres:/var/lib/postgresql/data"

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6380:6379"

volumes:
  postgres: